### ISSUE TITLE
 Inquiry Regarding Swarm Communication Mechanism in CrazyFlyt Project

### ISSUE THREAD

**Issue by khabelkacem** [jjshoots/CrazyFlyt#1]
Hello CrazyFlyt Developers,

I've been exploring the CrazyFlyt project and its capabilities, and I'm particularly interested in the potential for swarm communication within a given range. I've examined the provided examples, specifically in the examples directory, but I couldn't find any indications or case studies regarding swarm communication.  

Considering that CrazyFlyt is still in the developmental stage and is designed for flying real CrazyFlie 2.x drones with simulation support via the PyFlyt library, I am curious to know if there is any existing mechanism or planned feature for swarm communication. This could be crucial for implementing swarm behaviors such as flocking, where drones need to communicate and coordinate within a specified communication range.

Questions:

   - Is is possible currently to perform swarm communication within the CrazyFlyt project?
   - If so, could you kindly provide examples or case studies showcasing swarm communication and illustrating collective behaviors within the CrazyFlyt framework?

I appreciate the hard work and dedication you have put into the CrazyFlyt project, and I'm excited about its potential for drone development. Your insights into swarm communication within CrazyFlyt would be immensely helpful for the community and could open up new possibilities for collaborative drone applications.

Thank you for your time and consideration.

Best regards,

**Comment by jjshoots** [comment]
Hi! Thanks for the inquiry. To answer your questions:
1. CrazyFlyt is built on PyFlyt, with a very hackable interface. This means that implementing swarm communication shouldn't actually be too hard.
2. I can't think of any off the top of my head using CrazyFlyt, although I am aware of several being done within the PyFlyt library.

We are also actively looking for developers and interesting use cases, so if you'd like to elaborate more on your project, we'd be happy to assist in any way we can.
